CREATE TABLE IF NOT EXISTS tb_mesorregiao(
    CO_MESORREGIAO INTEGER PRIMARY KEY,
    NO_MESORREGIAO VARCHAR(100) NOT NULL,
    CO_UF INTEGER NOT NULL,
    FOREIGN KEY (CO_UF) REFERENCES tb_UF(CO_UF) 
);