CREATE TABLE IF NOT EXISTS tb_microrregiao(
    CO_MICRORREGIAO INTEGER PRIMARY KEY,
    NO_MICRORREGIAO VARCHAR(100) NOT NULL,
    CO_UF INTEGER NOT NULL,
    FOREIGN KEY (CO_UF) REFERENCES tb_UF(CO_UF) 
)