CREATE TABLE IF NOT EXISTS tb_municipio(
    CO_MUNICIPIO INTEGER PRIMARY KEY,
    NO_MUNICIPIO VARCHAR(150) NOT NULL,
    CO_UF INTEGER NOT NULL,
    FOREIGN KEY (CO_UF) REFERENCES tb_UF(CO_UF)
)
